require:
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/RenoFi/rubocop/main/ruby.yml
  - https://raw.githubusercontent.com/RenoFi/rubocop/main/rspec.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Naming/FileName:
  Exclude:
    - 'lib/*.rb'
