---
name: Bug report
about: Create a report to track an issue that has been identified
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Mutation/Query**

**URL and HTTP method (for non-GQL):**

**Sentry or Logs URL:**

**User/authentication details**
Impacted user name or service account

**Additional context**
Add any other context about the problem here.
